#!/usr/bin/perl -p

use open ':locale';
use utf8;

BEGIN {
$spaced = @ARGV && $ARGV[0] =~ /^-s|--spaced/ && shift;
$ascii  = @ARGV && $ARGV[0] =~ /^-a|--ascii/  && shift;
$morse_codes = q{
	A	•–
	B	–•••
	C	–•–•
	D	–••
	E	•
	F	••–•
	G	––•
	H	••••
	I	••
	J	•–––
	K	–•–
	L	•–••
	M	––
	N	–•
	O	–––
	P	•––•
	Q	––•–
	R	•–•
	S	•••
	T	–
	U	••–
	V	•••–
	W	•––
	X	–••–
	Y	–•––
	Z	––••
	0	–––––
	1	•––––
	2	••–––
	3	•••––
	4	••••–
	5	•••••
	6	–••••
	7	––•••
	8	–––••
	9	––––•
	.	•–•–•–
	,	––••––
	?	••––••
	'	•––––•
	!	–•–•––
	/	–••–•
	(	–•––•
	)	–•––•–
	&	• •••
	:	–––•••
	;	–•–•–•
	=	–•••–
	+	•–•–•
	-	–••••–
	_	••–– •–
	"	•–••–•
	$	•••–••–
	@	•––•–•
};

$morse_codes =~ s/^\s*(.*?)\s*$/$1/s;
%morse_codes = map { split(/\t/, $_, 2) } split(/\n\t/, $morse_codes);
}

foreach my $c (keys %morse_codes) {
	s/\Q$c\E/$morse_codes{$c} /ig;
}

s/(.)/$1 /g if $spaced;
tr/•–/.-/ if $ascii;
